### ISSUE TITLE
main builds, but tests don't pass; k3s problem?

### ISSUE THREAD

**Issue by squillace** [deislabs/containerd-wasm-shims#111]
Building from main from commit 5ca163a59a285d84ce88323e601e3d4f6b10e9a7 fails with the following on Ubuntu 22.04:

running 3 tests
 >>> curl http://localhost:8082/wws/hello
404 page not found

 >>> curl http://localhost:8082/spin/hello
 >>> curl http://localhost:8082/slight/hello
404 page not found

test wws_test ... ok
test spin_test ... ok
404 page not found

 >>> curl -X PUT http://localhost:8082/slight/set -d <value>
404 page not found

thread 'slight_test' panicked at 'assertion failed: `(left == right)`
  left: `"404 page not found\n"`,
 right: `"wyyauejuBVjpz34MYmSnjpMNmbczsJ"`', tests/integration_test.rs:48:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test slight_test ... FAILED

failures:

failures:
    slight_test

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.26s

error: test failed, to rerun pass `--test integration_test`
make: *** [Makefile:23: integration-tests] Error 101

**Comment by Mossaka** [comment]
@squillace just want to clarify: did you run the integration tests with the command `make integration_test`? 

`make integration_test` command not only invokes the `cargo test` command, but also sets up a k3s cluster and then tears it down after the tests finished.

**Comment by 0xE282B0** [comment]
Same here, CI test pipeline fails in `tests/integration_test.rs` with 404.

**Comment by 0xE282B0** [comment]
In my case, the pods weren't scheduled because there was almost no disk space left on the GitHub runner: 
```
Warning  FailedScheduling  25s   default-scheduler  0/3 nodes are available: 3 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
```

**Comment by Mossaka** [comment]
Should be fixed by now.
