### ISSUE TITLE
No print output from within Spin app

### ISSUE THREAD

**Issue by 0xE282B0** [deislabs/containerd-wasm-shims#123]
Hi,
While testing the shims on the `main` branch I found that I can't see print from within the HTTP handler anymore.

Simple example:
```Rust
use anyhow::Result;
use spin_sdk::{
    http::{Request, Response},
    http_component,
};

/// A simple Spin HTTP component.
#[http_component]
fn handle_hello_http(req: Request) -> Result<Response> {
    // #### This does not appear in log ####
    println!("{:?}", req.headers());
    // #############################
    Ok(http::Response::builder()
        .status(200)
        .header("foo", "bar")
        .body(Some("Hello, Fermyon".into()))?)
}
```

With [v0.8.0](https://github.com/deislabs/containerd-wasm-shims/releases/tag/v0.8.0) I can see the headers printed to the container log on every request. When using the shim from `main` there is no output. @Mossaka I guess it is related to the LibContainer change.

Btw. It's awesome that we have a Redis trigger now 😊

**Comment by Mossaka** [comment]
Umm it might be that we didn't pass in stdin, stdout, stderr for wiring up the std io.

**Comment by Mossaka** [comment]
I will take this as an action item to make our integration tests more robust on detecting HTTP headers.

**Comment by Mossaka** [comment]
Can you try it now? I think #121 resolved it

**Comment by Mossaka** [comment]
```
Serving http://0.0.0.0:80                                                                                                                                                                                                                                                                              
Available Routes:                                                                                                                                                                                                                                                                                    
  spin-dapr: http://0.0.0.0:80 (wildcard) 
```

Is this from `kubectl logs <pod>`?

**Comment by thangchung** [comment]
With `containerd-wasm-shims` v0.9.0 when I daprized it, then I couldn't see any logs from `spin` app. See image below

![image](https://github.com/deislabs/containerd-wasm-shims/assets/422341/76af4147-cc90-45af-b5ef-2cf505eb40d8)

@Mossaka @0xE282B0 Is it a bug?

**Comment by Mossaka** [comment]
I believe so. Will take a look today
