### ISSUE TITLE
spin + dapr demo

### ISSUE THREAD

**Issue by Mossaka** [deislabs/containerd-wasm-shims#130]
#121 adds the default executor to the spin shim to allow it run with Linux containers side-by-side in a pod. Now we need to add a demo for Spin + Dapr integration. 

@0xE282B0 are you interested in taking this issue?

**Comment by 0xE282B0** [comment]
Sure you can assign me.

I think a simple demo could be using the [Kubernetes Events](https://docs.dapr.io/reference/components-reference/supported-bindings/kubernetes-binding/) to trigger a Spin application that writes to Spin's [Key-Value Store](https://developer.fermyon.com/spin/kv-store-api-guide).

What other demos would you like to see? Maybe pub/sub with rabitmq or nats?

**Comment by Mossaka** [comment]
Sounds good to me!

**Comment by Mossaka** [comment]
@salaboy FYI
