### ISSUE TITLE
release v0.9.1

### ISSUE THREAD

**Issue by 0xE282B0** [deislabs/containerd-wasm-shims#154]
Hi all,
Since the v0.9.0 release, cgroups v1 support has been added, making the shims compatible with more kubernetes distributions https://github.com/KWasm/kwasm-node-installer/issues/43.

Could we do a v0.9.1 release where the artifacts can be downloaded from the release page?

**Comment by 0xE282B0** [comment]
Thank you!

**Comment by Mossaka** [comment]
Umm I was doing some smoke tests with the newly released k3d cluster `v0.9.1`. When I applied the workloads, I got this error 

```
Failed to pull image "ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.9.1": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.9.1": no match for platform in manifest: not found

```

**Comment by Mossaka** [comment]
It looks like the issue lies in the images that only support`wasi/wasm`.

If you change the container spec in `workload.yaml` to `ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.9.1@sha256:a1fb089c3452c509044ef82f0c7f81bbdb7b8dca5a8cb36d6268b0324c6fd8e3` for the spin shim, then it should work. 

However, this isn't ideal because we don't know the digest value until after they arepublished to a registry.

**Comment by mboersma** [comment]
I just noticed your comment, but already opened #159.

Is it possible to restore the `linux/amd64` layers? Having only `wasi/wasm` makes the demos harder to work with (I'm trying to update the shims and documentation in Kubernetes image-builder so we can continue to support Wasm in Cluster API).

Or perhaps we could update the `runtime.yaml` example to include the sha256 annotations? It's not reasonable for a user to figure these out IMHO.

**Comment by Mossaka** [comment]
I reverted the docker build action in #160 . 

It looked like we get linux/amd64 images https://github.com/deislabs/containerd-wasm-shims/pkgs/container/containerd-wasm-shims%2Fexamples%2Fspin-rust-hello/130079317?tag=v0.9.1

**Comment by Mossaka** [comment]
`v0.9.1` was just released. I did some smoking test and it looked fine!
