### ISSUE TITLE
failed to get sandbox runtime: no runtime for "spin" is configured (vanilla Kubernetes)

### ISSUE THREAD

**Issue by hotspoons** [deislabs/containerd-wasm-shims#165]
I have the spin shim installed on my worker nodes:
![image](https://github.com/deislabs/containerd-wasm-shims/assets/851973/5cdf685a-d0f0-40ea-b9d3-cb291a064e0b)

And the spin containerd plugin configured on my worker nodes:
![image](https://github.com/deislabs/containerd-wasm-shims/assets/851973/66b44ae3-e31b-4bdb-94a3-337b47a67aea)

The runtime class configured on my cluster:
![image](https://github.com/deislabs/containerd-wasm-shims/assets/851973/1e86c151-b824-4490-a491-412e858429d7)

This is the deployment config for the hello world app I was trying to get working:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"wasm-spin","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"wasm-spin"}},"template":{"metadata":{"labels":{"app":"wasm-spin"}},"spec":{"containers":[{"image":"ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:latest","name":"testwasm"}],"runtimeClassName":"wasmtime-spin-v1"}}}}
  creationTimestamp: "2023-10-11T01:42:09Z"
  generation: 1
  name: wasm-spin
  namespace: default
  resourceVersion: "75957"
  uid: 3104ba94-3ceb-496c-b7b3-23e6472500f3
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wasm-spin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wasm-spin
    spec:
      containers:
      - image: ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:latest
        imagePullPolicy: Always
        name: testwasm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      runtimeClassName: wasmtime-spin-v1
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-10-11T01:42:09Z"
    lastUpdateTime: "2023-10-11T01:42:09Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-10-11T01:42:09Z"
    lastUpdateTime: "2023-10-11T01:56:03Z"
    message: ReplicaSet "wasm-spin-58db6df759" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3

```

But this is what I get when trying to deploy any of the pods:

![image](https://github.com/deislabs/containerd-wasm-shims/assets/851973/0636982e-cc6e-4b5f-86ca-ddb444d64480)

Did I miss something? I tried with the fermyon helm chart and binaries from here, same result. Any help is appreciated. Thanks!

**Comment by Mossaka** [comment]
Sorry for the late reply. Given the screenshots I am not entirely sure what the issue was. Hence a few questions from my side to aid debugging:

1. Could you please check if the shim binary is indeed in the PATH of the worker nodes where containerd can find? 
2. Have you restarted containerd after you changed it's `config.toml`?
3. Can you please also check containerd logs to see if there are any interesging stuff? Please paste it here if you found something interesting.

**Comment by hotspoons** [comment]
> Sorry for the late reply. Given the screenshots I am not entirely sure what the issue was. Hence a few questions from my side to aid debugging:
> 
> 1. Could you please check if the shim binary is indeed in the PATH of the worker nodes where containerd can find?
> 2. Have you restarted containerd after you changed it's `config.toml`?
> 3. Can you please also check containerd logs to see if there are any interesging stuff? Please paste it here if you found something interesting.

Thank you for the help! I dug into the containerd logs as you recommended and that led me down a rabbit hole that ended me up on the Nvidia GPU operator GitHub issues page, where I found [this issue](https://github.com/NVIDIA/gpu-operator/issues/432#issuecomment-1761552867), and ultimately following the `Configure cgroups` section from [this guide](https://slateci.io/docs/cluster/manual/containerd.html) made the wasm shim work for my configuration.

Since this issue will be present on any out-of-the-box Enterprise Linux variant (e.g. Redhat, CentOS, Rocky, Alma) Kubernetes cluster, I would be happy to open a PR to add a note of warning to your documentation, hopefully it will save frustration for anyone who comes after me. Thank you!

**Comment by chokosabe** [comment]
Hi @hotspoons, I think I've run into this same issue using Rocky Linux 9. Was the cgroups Configuration the only thing you changed? Applied the changes to no effect.

Thanks in advance.

A.
