### ISSUE TITLE
Bug: static files are not accessible in spin shirm

### ISSUE THREAD

**Issue by michealch** [deislabs/containerd-wasm-shims#51]
Hey,

Pod Status is CrashLoopBackOff when **files** variable is added under component to access static files.
[Spin FileServer](https://github.com/fermyon/spin-fileserver) has same problem.

**Comment by Mossaka** [comment]
When the image is built, we assumed that at the root of the image filesystem, there could only be two files: a wasm module and a spin toml file. This is a restriction that we will probably lift off in the future as spin.toml supprts many components. With the current restriction, you really have to put the static files in a pod yaml file and inserted into the runtime's filesystem in order for spin to find the static assets to serve.
