### ISSUE TITLE
add --version flag to the CLI args

### ISSUE THREAD

**Issue by devigned** [deislabs/containerd-wasm-shims#60]
It would be nice to have a `--version` arg for the shims to be able to determine the build version information. Currently, there is no way to easily determine the version of the shim bin.

**Comment by Mossaka** [comment]
Can you elaborate more on where the `--version ` argument is passed to? 

This is the current behaviour:
![image](https://user-images.githubusercontent.com/5447827/218899298-75271206-81b2-4d72-9bd0-0660798436eb.png)

Do you envision instead of the above, it will prints out the version info?

**Comment by devigned** [comment]
Yes. It doesn't need to be `--version`, but in some way to be able to determine what version is running. In cases where we need to debug an issue, it would be super helpful for someone to easily determine the version / build of a shim on their system and then open an issue with that info.

**Comment by Mossaka** [comment]
I think `containerd-shim` is probably a better place to add the version flag. Here is an issue I created https://github.com/containerd/rust-extensions/issues/120

**Comment by Mossaka** [comment]
We should follow what's done in https://github.com/containerd/rust-extensions/pull/167 to bring the version flag to all the shims.

**Comment by Mossaka** [comment]
Close by #145
