### ISSUE TITLE
How to make capaiblities configurable at K8S for slight shim

### ISSUE THREAD

**Issue by huangyingting** [deislabs/containerd-wasm-shims#66]
I tried to deploy a slight wasm application into k8s cluster with kv redis capaiblity, however could not find a way to  make REDIS_ADDRESS configurable, it is defined in slightfile.yaml, by the time shim starts, it needs this file in place, so looks like no way to dynamically configure my redis address.

**Comment by Mossaka** [comment]
The slightfile can read REDIS_ADDRESS from enviornment variable, which you can pass the value of the address from pod yaml.

See https://github.com/deislabs/containerd-wasm-shims/blob/main/deployments/chat-workloads/workload.yaml#L21-L22
and https://github.com/deislabs/spiderlightning/blob/main/examples/keyvalue-demo/keyvalue_azblob_slightfile.toml#L7
