### ISSUE TITLE
Quickstart doesn't work

### ISSUE THREAD

**Issue by Tudor44** [deislabs/containerd-wasm-shims#85]
Hello ,

any update to this quickstart?
https://github.com/deislabs/containerd-wasm-shims/blob/main/containerd-shim-spin-v1/quickstart.md

When I run: `spin new qs-wasm-spin`
I got:
`Template qs-wasm-spin not found`

**Comment by Mossaka** [comment]
Can you try first running `spin template list` and then `spin new http-rust qs-wasm-spin`?

**Comment by Tudor44** [comment]
Sure , I get these lines but I have installed few templates previously:

<img width="518" alt="Screenshot 2023-04-01 at 14 24 21" src="https://user-images.githubusercontent.com/6132033/229288474-aa1c40a2-1fc6-4fe0-abad-f43eb442cd37.png">

**Comment by Mossaka** [comment]
You can install http-rust template using `spin template install`

**Comment by Mossaka** [comment]
Closing this issue now.
