### ISSUE TITLE
Quickstart spin container (qs-wasm-spin) doesn't start

### ISSUE THREAD

**Issue by Freakazoid182** [deislabs/containerd-wasm-shims#90]
I have been following the [spin quickstart tutorial](https://github.com/deislabs/containerd-wasm-shims/blob/main/containerd-shim-spin-v1/quickstart.md) and executing the steps exactly as described. I'm getting this error when trying to run the `qs-wasm-spin` container.
```
Error: failed to start containerd task "testwasm": Cannot read manifest file from "/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/testwasm/rootfs/spin.toml": unknown                            
```
The only difference with the example is that I've updated the `Dockerfile` to use rust `1.68.1` instead of `1.59` as noticed some issues with restoring the `spin-sdk` package on `1.59`.

The `spin.toml` file looks to be copied to the container just fine.

![image](https://user-images.githubusercontent.com/5238563/233778090-b73b83d2-6fc4-4108-bc18-d0d78e1a911b.png)

Strangely the example image works just fine:
```
ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.5.1
```
This image does also seem to contain the `spin_go_hello.wasm` file though, but I'm assuming that doesn't matter.

Is the quickstart demo still up to date?
Thanks for any help on this!

**Comment by Mossaka** [comment]
Close by #188
