### ISSUE TITLE
CI testing takes long time

### ISSUE THREAD

**Issue by Angelmmiguel** [deislabs/containerd-wasm-shims#91]
Hello 👋 

I recently open a PR to add a new [Wasm Workers Server shim](https://github.com/deislabs/containerd-wasm-shims/pull/88). When adding this new feature, I notice the CI time is growing consistently with every new shim due compilations and other required steps.

Comparing the builds in the different repos, the `wws` adds around +10 minutes of compilation times. And this may grow with new shims in the future.

I don't have any proposal as I didn't check the CI pipelines in depth. For now, I created this issue for tracking purposes :)

**Comment by Mossaka** [comment]
Maybe we can parallelize compilation for each of the shims.

**Comment by Angelmmiguel** [comment]
That would be a great initial improvement. 

In the previous community meeting we discussed about stop using `cross` and rely on containers for it. I would like to give it a try with Wasm Workers Server and extend it later to the rest of the shims :)

**Comment by Mossaka** [comment]
Resolved by #129
